name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Security'
    labels:
      - 'security'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependencies'

exclude-labels:
  - 'skip-changelog'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'chore'
      - 'maintenance'
      - 'documentation'
      - 'security'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/^feat/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/^chore/i'
  - label: 'dependencies'
    files:
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'package.json'
      - 'package-lock.json'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
